### ISSUE TITLE
[Feature Request] Ability to host from Apache or similar instead of internal webserver

### ISSUE THREAD

**Issue by Freddo3000** [Dahlgren/arma-server-web-admin#171] opened 2020-11-08 00:28 UTC
Title, would be useful to be able to host via (as an example) `abc.com/armaadmin/` instead of `abc.com:12345myport`, as well as the ability to use HTTPS, amongst other benefits.

**Comment by NocFA** [comment] 2020-11-08 00:30
You could just reverse proxy via Apache, which, is what I've done to enable the panel on my domain with SSL.

**Comment by Dahlgren** [comment] 2020-11-08 01:19
Duplicate of #170 

As mentioned there, you can also use a subdomain i.e. `arma.abc.com` -> `localhost:12345`

**Closed by Dahlgren** 2020-11-08 01:19 UTC

**Comment by Dahlgren** [comment] 2020-11-08 12:03
Here's an example of reverse proxy config for apache to get you started, https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension
